LOCAL_DIR := $(GET_LOCAL_DIR)

OBJECTS += \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/term.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/event.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/tty.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/ll.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/misc.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/log.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/lolcat.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/iboot.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/seq.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/io.o
