LOCAL_DIR := $(GET_LOCAL_DIR)

OBJECTS += \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/serial.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/config.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/device.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/menu.o \
	$(CURRENT_ROOT)/$(LOCAL_DIR)/iokit.o

WITH_UART_EXTRA ?= 0

OPTIONS += -DWITH_UART_EXTRA=$(WITH_UART_EXTRA)
